# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Header Configuration
avatar = "img/profile-picture.jpg"

#favicon
favicon = "icons/favicon.ico"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]
    enable = true
    repo = "ChienNQuang/ezaradise"
    repoId = "R_kgDOKJT0tQ"
    category = "Announcements"
    categoryId = "DIC_kwDOKJT0tc4C_Ip4"
    mapping = "pathname"
    strict = 0
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "top"
    theme = "preferred_color_scheme"
    lang = "en"
    lazyLoading = true